"""C++ header file generator for ESP32 HomeKey firmware projects."""

from __future__ import annotations

from datetime import datetime, timezone
from typing import TYPE_CHECKING

if TYPE_CHECKING:
    from .storage import HomeKeyStore


def format_cpp_byte_array(data: bytes, indent: str = "    ", bytes_per_line: int = 12) -> str:
    """Format binary buffer into C++ uint8_t hex array syntax."""
    hex_items = [f"0x{b:02X}" for b in data]
    lines = []
    for i in range(0, len(hex_items), bytes_per_line):
        chunk = hex_items[i : i + bytes_per_line]
        lines.append(indent + ", ".join(chunk))
    return ",\n".join(lines)


def generate_homekey_header(store: HomeKeyStore) -> str:
    """Generate homekeyc.h header file content from stored cryptographic credentials.
    
    Raises:
        ValueError: If SK.R is not provisioned.
    """
    if store.sk_r is None or store.pk_r is None or store.pk_r_x is None or store.gid is None:
        raise ValueError("HomeKey reader keys (SK.R) have not been provisioned by Apple Home yet.")

    sub_id = store.sub_id or b"\x00" * 8
    now_utc = datetime.now(timezone.utc).strftime("%Y-%m-%d %H:%M:%S UTC")

    lines: list[str] = []
    lines.append("// ============================================================================")
    lines.append("// Auto-generated Apple HomeKey Cryptographic Credentials (homekeyc.h)")
    lines.append(f"// Generated by Home Assistant Apple HomeKey BTHome Integration")
    lines.append(f"// Timestamp: {now_utc}")
    lines.append("// Target: ESP32 / HomeKey-ESP32 / DigitalDoorKey Firmware")
    lines.append("// ============================================================================")
    lines.append("#ifndef HOMEKEYC_H")
    lines.append("#define HOMEKEYC_H")
    lines.append("")
    lines.append("#include <stdint.h>")
    lines.append("#include <stddef.h>")
    lines.append("")
    lines.append("// ----------------------------------------------------------------------------")
    lines.append("// Reader Credentials")
    lines.append("// ----------------------------------------------------------------------------")
    lines.append("")
    lines.append("// Reader Private Key (32-byte SECP256R1 SK.R)")
    lines.append("const uint8_t HOMEKEY_READER_PRIVATE_KEY[32] = {")
    lines.append(format_cpp_byte_array(store.sk_r))
    lines.append("};")
    lines.append("")
    lines.append("// Reader Public Key (65-byte uncompressed SECP256R1 PK.R: 0x04 || X || Y)")
    lines.append("const uint8_t HOMEKEY_READER_PUBLIC_KEY[65] = {")
    lines.append(format_cpp_byte_array(store.pk_r))
    lines.append("};")
    lines.append("")
    lines.append("// Reader Public Key X-Coordinate (32 bytes PK.R_X)")
    lines.append("const uint8_t HOMEKEY_READER_PUBLIC_KEY_X[32] = {")
    lines.append(format_cpp_byte_array(store.pk_r_x))
    lines.append("};")
    lines.append("")
    lines.append("// Reader Group Identifier (8-byte GID = SHA-256(SK.R)[0..7])")
    lines.append("const uint8_t HOMEKEY_READER_GROUP_ID[8] = {")
    lines.append(format_cpp_byte_array(store.gid))
    lines.append("};")
    lines.append("")
    lines.append("// Reader Sub-Identifier (8 bytes)")
    lines.append("const uint8_t HOMEKEY_READER_SUB_ID[8] = {")
    lines.append(format_cpp_byte_array(sub_id))
    lines.append("};")
    lines.append("")
    lines.append("// ----------------------------------------------------------------------------")
    lines.append("// Device Endpoints & Issuer Credentials")
    lines.append("// ----------------------------------------------------------------------------")
    lines.append("")
    lines.append("typedef struct {")
    lines.append("    uint8_t issuer_id[8];")
    lines.append("    uint8_t endpoint_id[6];")
    lines.append("    uint8_t public_key[65]; // Uncompressed 0x04 || X || Y")
    lines.append("    uint8_t public_key_x[32];")
    lines.append("} homekey_endpoint_t;")
    lines.append("")
    
    endpoint_count = len(store.endpoints)
    lines.append(f"#define HOMEKEY_ENDPOINT_COUNT {endpoint_count}")
    lines.append("")

    if endpoint_count == 0:
        lines.append("// No endpoint credentials provisioned yet.")
        lines.append("const homekey_endpoint_t HOMEKEY_ENDPOINTS[1] = {")
        lines.append("    {")
        lines.append("        .issuer_id = {0x00, 0x00, 0x00, 0x00, 0x00, 0x00, 0x00, 0x00},")
        lines.append("        .endpoint_id = {0x00, 0x00, 0x00, 0x00, 0x00, 0x00},")
        lines.append("        .public_key = {0x00},")
        lines.append("        .public_key_x = {0x00}")
        lines.append("    }")
        lines.append("};")
    else:
        lines.append(f"const homekey_endpoint_t HOMEKEY_ENDPOINTS[{endpoint_count}] = {{")
        ep_blocks = []
        for ep in store.endpoints:
            iss_bytes = bytes.fromhex(ep["issuer_id"])
            ep_bytes = bytes.fromhex(ep["endpoint_id"])
            pk_bytes = bytes.fromhex(ep["public_key"])
            pk_x_bytes = bytes.fromhex(ep["public_key_x"])

            block = []
            block.append("    {")
            block.append("        .issuer_id = { " + ", ".join(f"0x{b:02X}" for b in iss_bytes) + " },")
            block.append("        .endpoint_id = { " + ", ".join(f"0x{b:02X}" for b in ep_bytes) + " },")
            block.append("        .public_key = {")
            block.append(format_cpp_byte_array(pk_bytes, indent="            "))
            block.append("        },")
            block.append("        .public_key_x = {")
            block.append(format_cpp_byte_array(pk_x_bytes, indent="            "))
            block.append("        }")
            block.append("    }")
            ep_blocks.append("\n".join(block))
        
        lines.append(",\n".join(ep_blocks))
        lines.append("};")

    lines.append("")
    lines.append("#endif // HOMEKEYC_H")
    lines.append("")
    return "\n".join(lines)
